cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

myshop/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path(_('cart/'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path(_('payment/'), include('payment.urls', namespace='payment')),
    path('rosetta/', include('rosetta.urls')),
    path('', include('shop.urls', namespace='shop')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _

app_name = 'orders'

urlpatterns = [
    path(_('create/'), views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
    path('order_list/', views.order_list, name='order_list'),
    path('order_list/<int:order_id>/order_details', views.order_details, name='order_details'),
    path('order_list/<int:order_id>/pdf/', views.order_pdf, name='order_pdf'),
]

orders/models.py
from django.db import models
from shop.models import *
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    first_name = models.CharField(_('first name'), max_length=50)
    last_name = models.CharField(_('last name'), max_length=50)
    email = models.EmailField(_('e-mail'))
    address = models.CharField(_('address'), max_length=250)
    postal_code = models.CharField(_('postal code'), max_length=20)
    city = models.CharField(_('city'), max_length=100)
    phone = models.CharField(max_length=20, default='+1')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    braintree_id = models.CharField(max_length=150, blank=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from django.db import transaction
from shop.models import *
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        # Order.Customer = Customer.objects.get(user=request.user)
        fields = ['first_name', 'last_name', 'email', 'phone', 'address',
                  'postal_code', 'city']

    # @transaction.atomic
    # def save(self):
    #
    #     Order.save()

orders/views.py
from django.urls import reverse
from django.shortcuts import render, redirect
from xhtml2pdf import pisa
import orders.models
from .models import OrderItem, Order
from .forms import OrderCreateForm
from cart.cart import Cart
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import get_object_or_404
from .models import *
from django.conf import settings
from django.template.loader import render_to_string, get_template
from shop.models import *
import os
from django.http import HttpResponse


@staff_member_required
def admin_order_pdf(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    html = render_to_string('orders/order/pdf.html',
                            {'order': order})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename=\
        "order_{}.pdf"'.format(order.id)
    # weasyprint.HTML(string=html).write_pdf(response,
    #                                        stylesheets=[weasyprint.CSS(
    #                                            settings.STATIC_ROOT + 'css/pdf.css')])
    return response


@staff_member_required
def admin_order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request,
                  'admin/orders/order/detail.html',
                  {'order': order})


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            user = request.user
            order.user = user
            order.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            # clear the cart
            cart.clear()
            # set the order in the session
            request.session['order_id'] = order.id
            # redirect for payment
            return redirect(reverse('payment:process'))

    else:
        form = OrderCreateForm()
    return render(request,
                  'orders/order/create.html',
                  {'cart': cart, 'form': form})


def order_list(request):
    currest_user=request.user
    orders=Order.objects.filter(user=currest_user.id)
    return render(request, 'orders/order/order_list.html', {'orders':orders})


def order_details(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'orders/order/order_details.html',{'order': order})


def order_pdf(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    # template=get_template('orders/order/pdf.html')
    template_path='orders/order/pdf.html'
    context={'order': order}
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="Invoice.pdf"'
    template = get_template(template_path)
    html = template.render(context)
    pisa_status = pisa.CreatePDF(
       html, dest=response, link_callback=order_list)
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

orders/templates/orders/order/create.html
{% extends "shop/base.html" %}
{% load i18n %}
{% block title %}
  {% trans "Checkout" %}
{% endblock %}

{% block content %}
  <h1>{% trans "Checkout" %}</h1>

  <div class="order-info">
    <h3>{% trans "Your order" %}</h3>
    <ul>
      {% for item in cart %}
        <li>
          {{ item.quantity }}x {{ item.product.name }}
          <span>${{ item.total_price }}</span>
        </li>
      {% endfor %}
    </ul>
    <p>{% trans "Total" %}: ${{ cart.get_total_price }}</p>
  </div>

  <form action="." method="post" class="order-form">
    {{ form.as_p }}

    <p><input type="submit" value="{% trans "Place order" %}"></p>
    {% csrf_token %}
  </form>
{% endblock %}

orders/templates/orders/order/created.html
{% extends "shop/base.html" %}
{% load i18n %}
{% block title %}
  {% trans "Thank you" %}
{% endblock %}

{% block content %}
  <h1>{% trans "Thank you" %}</h1>
 {% blocktrans with order_id=order.id %}
    <p>Your order has been successfully completed. Your order number is <strong>{{ order_id }}</strong>.</p>
  {% endblocktrans %}
{% endblock %}

orders/templates/orders/order/order_details.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}
    <body>
    <h3>Order Details</h3>
    <br>
    Invoice no. {{ order.id }}
    <span class="secondary">
        <br>
      Date: {{ order.created|date:"M d, Y" }}
    </span>
    <p></p>
    <p>
        {{ order.first_name }} {{ order.last_name }}<br>
        {{ order.email }}<br>
        {{ order.address }}<br>
        {{ order.postal_code }}, {{ order.city }}<br>
        {{ order.phone }}
    </p>

    <h3>Items bought</h3>
    <table>
        <thead>
        <tr>
            <th>Product</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Cost</th>
        </tr>
        </thead>
        <tbody>
        {% for item in order.items.all %}
            <tr class="row{% cycle "1" "2" %}">
                <td>{{ item.product.name }}</td>
                <td>${{ item.price }}</td>
                <td>{{ item.quantity }}</td>
                <td>${{ item.get_cost }}</td>
            </tr>
        {% endfor %}
        <tr class="total">
            <td colspan="3">Total</td>
            <td class="num">${{ order.get_total_cost }}</td>
        </tr>
        </tbody>
    </table>
    </body>
{% endblock %}

orders/templates/orders/order/order_list.html
{% extends 'shop/base.html' %}
{% load static %}
{% load i18n %}
{#<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">#}
{% block content %}

    <br>
    <div class="row">
        <h2 style="padding-left: 15Px">{% trans "Order List" %}</h2>
    </div>
    <br>
    <br>
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th>{% trans "Order ID" %}</th>
            <th>{% trans "Order date"%}</th>
            <th>{% trans "Amount" %}</th>
            <th>{% trans "Order Details" %}</th>
            <th>{% trans "PDF" %}</th>
        </tr>

        </thead>
        <tbody>
        {% for order in orders %}
            <tr>
                <td>{{ order.id }}</td>
                <td>{{ order.created }}</td>
                <td>{{ order.get_total_cost }}</td>
                <td><a href="{% url 'orders:order_details' order.id %}">view details</a></td>
                <td><a href="{% url 'orders:order_pdf' order.id %}">pdf</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

orders/templates/orders/order/pdf.html
{% load static %}
{% block content %}
    <head>
        <h3>Order Details</h3>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>
    <body>
    <br>
    Invoice no. {{ order.id }}
    <span class="secondary">
        <br>
      Date: {{ order.created|date:"M d, Y" }}
    </span>
    <p></p>
    <p>
        {{ order.first_name }} {{ order.last_name }}<br>
        {{ order.email }}<br>
        {{ order.address }}<br>
        {{ order.postal_code }}, {{ order.city }}<br>
        {{ order.phone }}
    </p>

    <h3>Items bought</h3>
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr>
            <th style="text-align:center;background-color:#a2d3f5;border:2px solid #060606;height:25px;">Product</th>
            <th style="text-align:center;background-color:#a2d3f5;border:2px solid #060606;height:25px;">Price</th>
            <th style="text-align:center;background-color:#a2d3f5;border:2px solid #060606;height:25px;">Quantity</th>
            <th style="text-align:center;background-color:#a2d3f5;border:2px solid #060606;height:25px;">Cost</th>
        </tr>
        </thead>
        <tbody>
        {% for item in order.items.all %}
            <tr class="row{% cycle "1" "2" %}">
                <td style="text-align:center;background-color:#ffffff;border:2px solid #060606;height:25px;">{{ item.product.name }}</td>
                <td style="text-align:center;background-color:#ffffff;border:2px solid #060606;height:25px;">${{ item.price }}</td>
                <td style="text-align:center;background-color:#ffffff;border:2px solid #060606;height:25px;">{{ item.quantity }}</td>
                <td style="text-align:center;background-color:#ffffff;border:2px solid #060606;height:25px;">${{ item.get_cost }}</td>
            </tr>
        {% endfor %}
        <tr class="total">
            <td colspan="3" style="text-align:center;background-color:#ffffff;border:2px solid #060606;height:25px;">Total</td>
            <td class="num" style="text-align:center;background-color:#ffffff;border:2px solid #060606;height:25px;">${{ order.get_total_cost }}</td>
        </tr>
        </tbody>
    </table>
    </body>
{% endblock %}