cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

myshop/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path(_('cart/'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path(_('payment/'), include('payment.urls', namespace='payment')),
    path('rosetta/', include('rosetta.urls')),
    path('', include('shop.urls', namespace='shop')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _

app_name = 'orders'

urlpatterns = [
    path(_('create/'), views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
    path('order_list/', views.order_list, name='order_list'),
    path('order_list/<int:order_id>/order_details', views.order_details, name='order_details'),
    path('order_list/<int:order_id>/pdf/', views.order_pdf, name='order_pdf'),
]

shop/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'shop'

urlpatterns = [
    path('api/order_info', views.order_info.as_view()),
    path('api/categorys_info', views.category_info.as_view()),
    path('api/users_info', views.user_info.as_view()),
    path('api/products_info', views.product_infos.as_view()),
    # path('',views.home,name='home'),
    path('', views.product_list, name='product_list'),
    # path('', views.login,name='login'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail,
         name='product_detail'),
    path('signup', views.CustomerSignUpView, name='signup'),
    path('signup/signup_successful', views.signup_successful, name='signup_successful'),
    path('accounts/password_reset/',
         auth_views.PasswordResetView.as_view(template_name="registration/password_reset.html"), name='password_reset'),
    path('accounts/password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name="registration/reset_email_sent.html"),
         name='reset_email_sent'),
    path('accounts/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="registration/reset_confirm.html"),
         name='reset_confirm'),
    path('accounts/reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name="registration/reset_complete.html"),
         name='reset_complete'),
    path('accounts/password_change/',
         auth_views.PasswordChangeView.as_view(template_name="registration/password_change.html"),
         name='password_change'),
    path('accounts/password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name="registration/password_changed.html"),
         name='password_changed'),
    path('visitor_new', views.visitor_new, name='visitor_new'),
    path('about', views.about, name='about'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
from django_countries.fields import CountryField
# from parler.models import TranslatableModel, TranslatedField


class User(AbstractUser):
    is_customer = models.BooleanField(default=False)


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    address = models.CharField(max_length=150, blank=True)
    city = models.CharField(max_length=50, blank=True)
    state = models.CharField(max_length=50, blank=True)
    zipcode = models.CharField(max_length=50, blank=True)
    phone = models.CharField(blank=True, max_length=20)


class Category(models.Model):
    name = models.CharField(max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])


class Currency(models.Model):
    selectedcountry = CountryField(blank_label='(select country)')


class Feedback(models.Model):
    Name = models.CharField(max_length=200)
    Comments_Or_Questions = models.CharField(max_length=500)
    Email = models.EmailField(max_length=200)
    Phone_Number = models.CharField(max_length=20, null=False)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.Name

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.forms.utils import ValidationError
from django.forms.widgets import DateInput
from .models import *
from django_countries.widgets import CountrySelectWidget



class CustomerSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_customer = True
        user.save()
        Customer.objects.create(user=user)
        return user


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('address', 'city', 'state', 'zipcode', 'phone')


class CountryForm(forms.ModelForm):
    class Meta:
        model = Currency
        fields = ('selectedcountry',)
        widgets = {'selectedcountry': CountrySelectWidget()}

class VisitorForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ('Name', 'Comments_Or_Questions', 'Email', 'Phone_Number')

shop/views.py
from datetime import timedelta

from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from .models import Category, Product, User, Currency
from cart.forms import CartAddProductForm
from .forms import *
import requests
import json
import pycountry
from django.shortcuts import get_object_or_404
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializers import *
from rest_framework import status
from .models import *
from rest_framework.permissions import IsAdminUser
from orders.models import Order


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    # initialize currency as Euro
    selected_country = "DE"
    country_form = CountryForm()

    # pull selected country
    if request.method == 'POST':
        selected_country = request.POST['selectedcountry']

    # get appropriate currency
    countryname = pycountry.countries.get(alpha_2=selected_country)
    currency = pycountry.currencies.get(numeric=countryname.numeric)
    try:
        currencycode = currency.alpha_3
    except:
        currencycode = 'EUR'
    else:
        currencycode = currency.alpha_3

    # pull current rate
    r1string = 'https://api.getgeoapi.com/v2/currency/convert?api_key=6e1e62d64cbc5f6cec2a8cae8dbd34cd38953e6a&from=USD&to='
    r2string = currencycode
    r3string = '&format=json'
    apistring = r1string + r2string + r3string
    response = requests.get(apistring)
    exchangerate = response.json()
    extrate = exchangerate['rates']
    exttrate = extrate[currencycode]
    exrate = exttrate['rate']

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'country_form': country_form,
                   'categories': categories,
                   'products': products,
                   'exrate': exrate,
                   'currencycode': currencycode
                   })


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()

    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form,
                   })


# -----------------------------------------------------
def CustomerSignUpView(request):
    model = User
    form_class = CustomerSignUpForm
    form = CustomerSignUpForm
    if request.method == 'POST':
        form = CustomerSignUpForm(request.POST)
        if form.is_valid():
            is_customer = True
            form.save()
            return redirect('shop:signup_successful')
        else:
            context = {'form': form}
            return render(request, 'registration/signup.html', context)
    else:
        context = {'form': form}
        return render(request, 'registration/signup.html', context)


def signup_successful(request):
    return render(request, 'registration/signup_successful.html', {'shop': signup_successful})


class category_info(APIView):
    permission_classes = [IsAdminUser]

    def get(self, request):
        c1 = Category.objects.all()
        s1 = cSerializer(c1, many=True)
        return Response(s1.data)


class user_info(APIView):
    permission_classes = [IsAdminUser]

    def get(self, request):
        c1 = User.objects.all()
        s1 = uSerializer(c1, many=True)
        return Response(s1.data)


class product_infos(APIView):
    permission_classes = [IsAdminUser]

    def get(self, request):
        c1 = Product.objects.all()
        s1 = pSerializer(c1, many=True)
        return Response(s1.data)


class order_info(APIView):
    permission_classes = [IsAdminUser]

    def get(self, request):
        c1 = Order.objects.all()
        s1 = oSerializer(c1, many=True)
        return Response(s1.data)


# def login(request):
#     return render(request, 'registration/login.html', {'shop': login})

def visitor_new(request):
    if request.method == "POST":
        form = VisitorForm(request.POST)
        if form.is_valid():
            visitors = form.save(commit=False)
            visitors.created_date = timezone.now()
            visitors.save()
            return render(request, 'shop/product/feedback_done.html')

    else:
        form = VisitorForm()
        # print("Else")
    return render(request, 'shop/product/contactus.html', {'form': form})


def about(request):
    return render(request, 'shop/product/aboutus.html')

shop/templates/shop/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <div id="header">
  <a href="/" class="logo">{% trans "E-Buy" %}</a>
  {% get_current_language as LANGUAGE_CODE %}
  {% get_available_languages as LANGUAGES %}
  {% get_language_info_list for LANGUAGES as languages %}
  <div class="languages">
    <p>{% trans "Language" %}:</p>
    <ul class="languages">
      {% for language in languages %}
        <li>
          <a href="/{{ language.code }}/"
          {% if language.code == LANGUAGE_CODE %} class="selected"{% endif %}>
            {{ language.name_local }}
          </a>
        </li>
      {% endfor %}
    </ul>
  </div>
</div>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
            crossorigin="anonymous"></script>
{#    /*<title>{% block title %}My shop{% endblock %}</title>*#}
    <link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
    <a href={% url 'shop:product_list' %} class="navbar-brand">
        <img src="{% static 'img/eBuy.png' %}" height="60" alt="CoolBrand">
    </a>
    <a class="navbar-brand" href={% url 'shop:product_list' %}>{% trans "E-Buy" %}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <li class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href={% url 'shop:product_list' %}>{% trans "Home" %} <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href={% url 'shop:product_list' %}>{% trans "Products" %}<span
                        class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href={% url 'shop:about'%}>{% trans "About Us" %}<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href={% url 'shop:visitor_new'%}>{% trans "Contact Us" %}<span class="sr-only">(current)</span></a>
            </li>
        </ul>
{#        <form class="form-inline my-2 my-lg-0">#}
    <ul class="navbar-nav">
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                    </button>
                    <div class="dropdown-menu dropdown-menu-right">
                    <a href="{% url 'orders:order_list' %}" class="dropdown-item">{% trans "Orders" %}</a>
                    <a href="{% url 'shop:password_change' %}" class="dropdown-item">{% trans "Change password"%}</a>
                    <a href="{% url 'logout' %}" class="dropdown-item">{% trans "Logout" %}</a>
                </div>
                </li>
            {% else %}
                <a href="{% url 'login' %}" class="btn btn-secondary ml-2" role="button"
                   aria-pressed="true">login</a>
                <a href="{% url 'shop:signup' %}" class="btn btn-secondary ml-2" role="button"
                   aria-pressed="true">Signup</a>
            {% endif %}
{#    </form>#}
    </ul>
    </li>
</nav>
{% if user.is_authenticated %}
    <div id="subheader">
        <div class="cart">
            {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                    {% trans "Your cart" %}:
                   <a href="{% url "cart:cart_detail" %}">
                      {% blocktrans with total=cart.get_total_price count items=total_items %}
                         {{ items }} item, ${{ total }}
                     {% plural %}
                          {{ items }} items, ${{ total }}
                      {% endblocktrans %}
                   </a>
                {% else %}
                    {% trans "Your cart is empty." %}
                {% endif %}
            {% endwith %}
        </div>
    </div>
{% endif %}
<div id="content">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>